[package]
name = "tetris-rust"
version = "0.1.0"
authors = ["Carsten König <Carsten.Koenig@hotmail.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
piston_window = "0.113.0"
